# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-14 20:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import otree.db.models
import otree_save_the_change.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('otree', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_subsession', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selfre_getorders_group', to='otree.Session')),
            ],
            options={
                'db_table': 'selfre_GetOrders_group',
            },
            bases=(otree_save_the_change.mixins.SaveTheChange, models.Model),
        ),
        migrations.CreateModel(
            name='Orderapi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idx', otree.db.models.IntegerField(null=True)),
                ('region', otree.db.models.StringField(default='Region X', max_length=10000, null=True)),
                ('bid', otree.db.models.PositiveIntegerField(default=0, null=True)),
                ('bidvol', otree.db.models.IntegerField(default=0, null=True)),
                ('offer', otree.db.models.IntegerField(default=1000, null=True)),
                ('offervol', otree.db.models.IntegerField(default=0, null=True)),
            ],
            options={
                'db_table': 'selfre_GetOrders_orderapi',
            },
            bases=(otree_save_the_change.mixins.SaveTheChange, models.Model),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_group', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_payoff', otree.db.models.CurrencyField(default=0, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_gbat_arrived', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('_gbat_grouped', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('name', otree.db.models.StringField(max_length=10000, null=True)),
                ('description', otree.db.models.StringField(max_length=10000, null=True)),
                ('bid', otree.db.models.PositiveIntegerField(default=0, null=True)),
                ('bidvol', otree.db.models.PositiveIntegerField(default=0, null=True)),
                ('offer', otree.db.models.PositiveIntegerField(default=100, null=True)),
                ('offervol', otree.db.models.PositiveIntegerField(default=0, null=True)),
                ('pos', otree.db.models.IntegerField(default=0, null=True)),
                ('money', otree.db.models.CurrencyField(default=0, null=True)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='selfre_GetOrders.Group')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selfre_getorders_player', to='otree.Participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selfre_getorders_player', to='otree.Session')),
            ],
            options={
                'db_table': 'selfre_GetOrders_player',
            },
            bases=(otree_save_the_change.mixins.SaveTheChange, models.Model),
        ),
        migrations.CreateModel(
            name='Subsession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selfre_getorders_subsession', to='otree.Session')),
            ],
            options={
                'db_table': 'selfre_GetOrders_subsession',
            },
            bases=(otree_save_the_change.mixins.SaveTheChange, models.Model),
        ),
        migrations.AddField(
            model_name='player',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='selfre_GetOrders.Subsession'),
        ),
        migrations.AddField(
            model_name='orderapi',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='selfre_GetOrders.Player'),
        ),
        migrations.AddField(
            model_name='group',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='selfre_GetOrders.Subsession'),
        ),
    ]
