# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-13 17:29
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('selfre_GetOrders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='groupfreight',
            field=otree.db.models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='minfreight',
            field=otree.db.models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='pnl',
            field=otree.db.models.CurrencyField(default=0, null=True),
        ),
    ]
